# Generated by Django 2.2.4 on 2020-11-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
